# 关闭禁用防火墙

- name: Disable and stop firewalld on CentOS
  when: ansible_facts['os_family'] == 'RedHat'
  systemd_service:
    name: firewalld
    state: stopped
    enabled: no


- name: Disable and stop ufw on Ubuntu
  when: ansible_facts['os_family'] == 'Debian'
  systemd_service:
    name: ufw
    state: stopped
    enabled: no