# 关闭禁用SELinux
- name: Ensure SELinux is disabled
  selinux:
    state: disabled

- name: Ensure SELinux config is updated to be disabled
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'
    state: present