- name: Install dnf packages
  package:
    name:
      - vim
      - wget
      - nc
      - net-tools
      - yum-utils
      - lrzsz
      - gcc
      - bc
      - bzip2
      - libcgroup
      - lsof
      - gdb
      - expect
      - libcgroup-devel
      - libcgroup-pam
      - libcgroup-tools
      - numactl
      - sshpass
      - rsync
    state: present
