# 下载软件
- name: Download file with check (md5)
  get_url:
    url: https://cdn.mysql.com//Downloads/MySQL-8.4/mysql-8.4.3-linux-glibc2.28-x86_64.tar.xz
    dest: /tmp
    checksum: md5:0d7f2af1ac4fa3afca87608a3dec5596

# 解压软件包
- name: Extract mysql tarball
  unarchive:
    src: /tmp/mysql-8.4.3-linux-glibc2.28-x86_64.tar.xz
    dest: /mysql/mysoft/
    remote_src: yes


# 修改/mysql目录权限
- name: Change permissions of /mysql
  file:
    path: /mysql
    state: directory
    mode: '0755'
    owner: mysql
    group: mysql
    recurse: true