# 兼容模式
- name:  initnodedatamap
  shell: 'source ~/.bash_profile; gccli -ugbase -pgbase20110531 -e" initnodedatamap;"'
  become: true
  become_user: gbase
  tags:
    - normal

- name:  Set root Password
  shell: 'source ~/.bash_profile; gccli -ugbase -pgbase20110531 -e"set password for root = password(''{{dba_password }}'');"'
  become: true
  become_user: gbase
  tags:
    - normal

- name:  Set gbase Password
  shell: 'source ~/.bash_profile; gccli -ugbase -pgbase20110531 -e"set password for gbase = password(''{{dba_password }}'');"'
  become: true
  become_user: gbase
  tags:
    - normal

# 多VC模式
- name:  initnodedatamap
  shell: 'source ~/.bash_profile; gccli -ugbase -pgbase20110531 -D{{ vc_name }}. -e" initnodedatamap;"'
  become: true
  become_user: gbase
  tags:
    - virtual

- name:  Set root Password
  shell: 'source ~/.bash_profile; gccli -ugbase -pgbase20110531 -D{{ vc_name }}. -e"set password for root = password(''{{dba_password }}'');"'
  become: true
  become_user: gbase
  tags:
    - virtual

- name:  Set gbase Password
  shell: 'source ~/.bash_profile; gccli -ugbase -pgbase20110531 -D{{ vc_name }}. -e"set password for gbase = password(''{{dba_password }}'');"'
  become: true
  become_user: gbase
  tags:
    - virtual


# ALTER USER user() IDENTIFIED BY 'Mysql80!';
# CREATE USER 'zhang'@'%' IDENTIFIED BY 'Zhang123!';
# GRANT ALL PRIVILEGES ON *.* TO 'zhang'@'%' WITH GRANT OPTION;
# FLUSH PRIVILEGES;