# 生成demo.options文件
- name: demo.options
  template: 
    src: demo.options.j2
    dest: /opt/gbase_workspace/setup/gcinstall/demo.options
    owner: gbase
    group: gbase
    
# 执行gcinstall.py
- name:  python gcinstall.py
  shell: |
    cd /opt/gbase_workspace/setup/gcinstall &&
    echo -e "Y\nY\nY" | /usr/bin/python2 gcinstall.py --silent=demo.options
  become: true
  become_user: gbase

# 二次执行SetSysEnv
- name: Execute Python script
  command: 
    "python /tmp/SetSysEnv.py --installPrefix=/opt --dbaUser=gbase --cgroup"

#################多VC模式####################################
# 生成create_vc.xml文件    
- name: create_vc.xml
  template: 
    src: create_vc.xml.j2
    dest: /opt/gbase_workspace/setup/gcinstall/create_vc.xml
    owner: gbase
    group: gbase
  tags:
    - virtual

# 执行create_vc.xml 
- name:  gcadmin createvc
  shell: |
    source ~/.bash_profile &&
    cd /opt/gbase_workspace/setup/gcinstall &&
    gcadmin createvc create_vc.xml
  become: true
  become_user: gbase
  tags:
    - virtual
#################多VC模式####################################

# 生成gcChangeInfo.xml文件    
- name: gcChangeInfo.xml
  template: 
    src: gcChangeInfo.xml.j2
    dest: /opt/gbase_workspace/setup/gcinstall/gcChangeInfo.xml
    owner: gbase
    group: gbase

# 执行gcChangeInfo.xml
- name:  gcadmin distribution
  shell: 'source /home/gbase/.bash_profile; gcadmin distribution /opt/gbase_workspace/setup/gcinstall/gcChangeInfo.xml p 1 d 1 db_user gbase db_pwd {{ dbaPwd }}'
  become: true
  become_user: gbase