# 创建Gbase安装路径
- name: Create directory /opt/gbase_workspace/setup
  file:
    path: "{{ item }}"
    owner: gbase
    group: gbase
    mode: '0755'
    state: directory
  with_items:
    - /opt/gbase_workspace/setup
    - /opt/gbase_workspace/tools

# 上传文件
- name: Upload Files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: gbase
    group: gbase
    mode: '0644'
  with_items:
      - { src: 'c3-5.1.2-1.noarch.rpm', dest: '/opt/gbase_workspace/tools' }
      - { src: 'GBase8a_MPP_Cluster-NoLicense-9.5.3.27.20_patch.9-redhat7-x86_64.tar.bz2', dest: '/tmp' }

# 安装C3工具
- name: Install C3.rpm 
  shell: "cd /opt/gbase_workspace/tools; rpm -ivh --force c3-5.1.2-1.noarch.rpm"

# 配置C3.conf
- name: c3.conf
  template: 
    src: c3.conf.j2
    dest: /etc/c3.conf
    owner: gbase
    group: gbase

# 解压软件包
- name: Extract Gbase tarball
  unarchive:
    src: /tmp/GBase8a_MPP_Cluster-NoLicense-9.5.3.27.20_patch.9-redhat7-x86_64.tar.bz2
    dest: /opt/gbase_workspace/setup
    remote_src: yes

# 配置开机启动
- name: Add gcware_services on rc.local
  lineinfile:
    dest: /etc/rc.d/rc.local
    line: "su - gbase -c gcware_services all start"
    insertafter: EOF
    state: present